config/routes.rb
Rails.application.routes.draw do

  root 'dash_boards#index'
  resources :vendors do
    collection do
      get 'fetch_vendor_amount'
      get 'delete_vendor_amount'
    end
  end
  resources :sale_reports, only: [:index, :destroy]
  resources :product_reports
  resources :vendor_reports
  resources :purchased_item_reports
  resources :purchased_sale_reports
  resources :purchased_items do
    collection do
      get 'excel_upload'
      post 'import_items'
      post 'get_barcode'
      get 'fetch_product_detail'
      get 'fetch_barcode_detail'
    end
  end
  resources :products do
    collection do
      get 'fetch_product_vendor_wise'
      get 'excel_upload'
      post 'import_products'
      get 'append_product'
      get 'append_vendor'
      get 'fetch_product_detail'
    end
  end
  get 'billing', to: 'billings#get_billing_form'
  get 'billing_for_kitchen', to: 'kitchen_billings#get_billing_form'
  get 'kitchen_billings/append_items', to: 'kitchen_billings#append_items'
  get 'kitchen_billings/fetch_item_detail', to: 'kitchen_billings#fetch_item_detail'
  post 'billings/billing_for_product', to: 'billings#billing_for_product'
  get 'purchased_billing', to: 'purchased_billings#get_billing_form'
  post 'purchased_billings/billing_for_product', to: 'purchased_billings#billing_for_product'
  devise_for :admins
  resources :kitchens do
    collection do
      get 'fetch_menu_category_wise'
    end
  end

end

app/models/purchased_item.rb
class PurchasedItem < ApplicationRecord

  def self.import_product(file)
    temp_sheet = open_spreadsheet(file)
    return false if temp_sheet == false
    spreadsheet = temp_sheet.sheet('Purchased Items') rescue nil
    return false if spreadsheet == nil
    result = insert_data_to_database spreadsheet
    return false unless result.present?
    PurchasedItem.import result
    true
  end

  def self.open_spreadsheet file
    case File.extname(file.original_filename)
    when ".csv" then Csv.new(file.path, nil, :ignore)
    when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
    when ".xlsx" then Roo::Excelx.new(file.path)
    else return false
    end
  end

  def self.insert_data_to_database spreadsheet
    @purchased_items = []
    spreadsheet.each.with_index do |sheet, index|
      skip = [1,2,3]
      next if skip.include? index
      next if sheet[1] == "" || sheet[2] == "" || sheet[3] == "" || sheet[5] == "" || sheet[6] == "" || sheet[7] == "" || sheet[1] == nil || sheet[3] == nil || sheet[3] == nil || sheet[5] == nil || sheet[6] == nil || sheet[7] == nil
      @purchased_items << PurchasedItem.new(item_name: sheet[1], item_price: sheet[2], item_barcode: sheet[4], purchased_from: sheet[7], quantity: sheet[3], category: sheet[5], mode_of_payment: sheet[6])
    end
    @purchased_items
  end

end

app/controllers/purchased_items_controller.rb
class PurchasedItemsController < ApplicationController
  before_action :authenticate_admin!
  before_action :load_item, only: [:show, :edit, :update, :destroy]

  def index
    @ourchased_items = PurchasedItem.all
  end

  def new
    @ourchased_item = PurchasedItem.new
  end

  def edit

  end

  def create
    @ourchased_item = PurchasedItem.new(purchased_item_params)
    if @ourchased_item.save
      flash[:success] = "Item created successfully!"
      redirect_to purchased_items_path
    else
      flash[:danger_messages] = @ourchased_item.errors.full_messages
      render :new
    end
  end

  def update
    if @ourchased_item.update(purchased_item_params)
      flash[:success] = "Item updated successfully!"
      redirect_to purchased_items_path
    else
      flash[:danger_messages] = @ourchased_item.errors.full_messages
      render :edit
    end
  end

  def destroy
    @ourchased_item.destroy
    flash[:success] = "Item deleted successfully!"
    redirect_to purchased_items_path
  end

  def excel_upload
    @co_header = "Excel Upload"
  end

  def import_items
    if PurchasedItem.import_product(params[:file])
      flash[:success] = "Product Uploaded Successfully!"
      redirect_to purchased_items_path
    else
      flash[:danger] = "Invalid Template!"
      redirect_to excel_upload_purchased_items_path
    end
  end

  def fetch_product_detail
    result = []
    if params[:product_id].present? && params[:product_id].to_i != 0
      product = PurchasedItem.find_by(id: params[:product_id].to_i)
      result << product.id << product.item_name << product.item_price << product.quantity
    end
    respond_to do |format|
      format.json { render json: result.to_json }
    end
  end

  def fetch_barcode_detail
    result = []
    product = PurchasedItem.where(item_barcode: params[:barcode]).first
    result << product.id << product.item_name << "Rs.#{sprintf "%.2f", product.item_price.to_f}" << product.quantity if product.present?
    respond_to do |format|
      format.json { render json: result.to_json }
    end
  end

  def billing_for_product

  end

  private

  def load_item
      @ourchased_item = PurchasedItem.find(params[:id])
    end

  def purchased_item_params
    params.require(:purchased_item).permit(:item_name, :item_price, :item_barcode, :purchased_from, :quantity, :category, :mode_of_payment)
  end

end

app/helpers/purchased_items_helper.rb
module PurchasedItemsHelper
end

app/views/purchased_items/_form.html.erb
<%= form_with model: @ourchased_item, local: true do |f| %>
  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-3">
      <%= f.label :item_name, "Name", class: "required-field" %><br>
      <%= f.text_field :item_name , class: "form-control", required: true, placeholder: "Enter Item Name" %>
    </div>
    <div class="col-md-3">
      <%= f.label :item_price, 'Price (Rs.)', class: "required-field" %><br>
      <%= f.number_field :item_price , class: "form-control", required: true, placeholder: "Enter price" %>
    </div>
    <div class="col-md-3">
      <%= f.label :quantity, class: "required-field" %><br>
      <%= f.number_field :quantity, class: "form-control", required: true, placeholder: "Enter Quantity" %>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-3">
      <%= f.label :category, class: "required-field" %><br>
      <%= f.text_field :category, class: "form-control", required: true, placeholder: "Enter Category" %>
    </div>
    <div class="col-md-3">
      <%= f.label :item_barcode, "Barcode" %><br>
      <%= f.text_field :item_barcode, class: "form-control", placeholder: "Enter Barcode" %>
    </div>
    <div class="col-md-3">
      <%= f.label :mode_of_payment, class: "required-field" %><br>
      <%= f.select :mode_of_payment, options_for_select(["Cash", "Paytm", "PhonePe", "Google Pay", "Online Banking", "Other"], @ourchased_item.mode_of_payment), {prompt: "Select Mode of payment"}, { class: 'form-control', required: true } %>
    </div>
  </div><br>
  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-3">
      <%= f.label :purchased_from, "Purchased From", class: "required-field" %><br>
      <%= f.text_field :purchased_from, class: "form-control", required: true, placeholder: "Purchased From Ex: Example pvt ltd" %>
    </div>

  </div><br>

  <br>
  <center><%= f.submit "#{@ourchased_item.new_record? ? 'Add Item' : 'Update Item'}", class: "btn btn-success" %></center><br>
  <center><%= link_to "Back", :back %></center>
<% end %>
<script type="text/javascript">
  $(document).ready(function() {
  $('#product_vendor_id').select2({
    placeholder: "Choose a Vendor"
  });
});
</script>
<style type="text/css">
  body {
    background: #E3E6E3;
  }
</style>

app/views/purchased_items/edit.html.erb
<% content_for :co_header do %>
  <div class="row co-header">
    <div class="col-md-3">
      <div>Edit Purchased Item</div>
    </div>
    <div class="col-md-6"></div>
    <div class="col-md-3">
    </div>
  </div>
<% end %>
<%= render "form" %>

app/views/purchased_items/excel_upload.html.erb
<% content_for :co_header do %>
  <div class="row co-header">
    <div class="col-md-3">
      <div>Purchased Items > Excel Upload</div>
    </div>
    <div class="col-md-3">
    </div>
    <div class="col-md-3">
    </div>
    <div class="col-md-3">
      <div><%= link_to "Add Product", new_purchased_item_path, class: "btn btn-success btn-xs", style: "margin-left:-30px;margin-top:-8px;"%></div>
    </div>
  </div>
<% end %>
<br><br><br>
<%= form_tag import_items_purchased_items_path, multipart: true, id: "upload-excel-product" do %>
  <br>
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4"><%= image_tag('upload.png', class: "image-excel-upload")%></div>
    <div class="col-md-4"></div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <%= file_field_tag :file, class: "upload-field", required: true%>
    </div>
    <div class="col-md-4"></div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-1">
      <%= link_to "Close", purchased_items_path, class: "btn btn-danger btn-xs back" %>
    </div>
    <div class="col-md-4">
      <%= submit_tag "Upload", class: "btn btn-success btn-xs", id: "submit-upload" %>

    </div>
    <div class="col-md-3"></div>
  </div>
  <br>
<% end %>
<style type="text/css">
  .back {
    margin-left: 220px;
  }
  .image-excel-upload{
    margin-left: -20px
  }
  #submit-upload{
    margin-left: -7px;
  }
  .upload-field {
    border: 2px solid gray;
    color: gray;
    margin-left:-47px;
    background-color: white;
    padding: 8px 10px;
    border-radius: 8px;
    font-size: 13px;
    font-weight: bold;
  }
  #upload-excel-product {
    width: 550px;
    margin-left:230px;
    /*background-color: grey;*/
    border-style: dotted
  }
</style>

app/views/purchased_items/index.html.erb
<% content_for :co_header do %>
  <div class="row co-header">
    <div class="col-md-3">
      <div>Purchased Items</div>
    </div>
    <div class="col-md-3">
    </div>
    <div class="col-md-3">
    </div>
    <div class="col-md-3">
      <div><%= link_to "Add Item", new_purchased_item_path, class: "btn btn-success btn-xs", style: "margin-left:-30px;margin-top:-8px;"%></div>
    </div>
  </div>
<% end %>
<table id="custom-table">
  <thead>
    <tr>
      <th>SI No.</th>
      <th>Name</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Barcode</th>
      <th>Category</th>
      <th>Mode of Payment</th>
      <th>Purchased From</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% if @ourchased_items.present? %>
      <% count = 0 %>
      <% @ourchased_items.each do |item|%>
        <% count += 1 %>
        <tr>
          <td><%= count %></td>
          <td><%= item.item_name %></td>
          <% price = item.item_price.present? ? item.item_price : 0 %>
          <td><%= "Rs.#{number_with_precision(price, precision: 2)}" %></td>

          <td><%= item.quantity %></td>
          <td><%= item.item_barcode %></td>
          <td><%= item.category %></td>
          <td><%= item.mode_of_payment %></td>
          <td><%= item.purchased_from %></td>
          <td><center><%= link_to image_tag("edit.png"), edit_purchased_item_path(item) %></center></td>
          <td><center><%= link_to image_tag("trash.png"), purchased_item_path(item), method: :delete, data: { confirm: 'Do you want to delete this Item?' } %></center></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<script type="text/javascript">
  $(document).ready( function () {
    $('#custom-table').DataTable();
  });
</script>

app/views/purchased_items/new.html.erb
<% content_for :co_header do %>
  <div class="row co-header">
    <div class="col-md-3">
      <div>New Purchased Item</div>
    </div>
    <div class="col-md-6"></div>
    <div class="col-md-3">
    </div>
  </div>
<% end %>
<%= render "form" %>