config/routes.rb
Rails.application.routes.draw do

  root 'dash_boards#index'
  resources :vendors do
    collection do
      get 'fetch_vendor_amount'
      get 'delete_vendor_amount'
    end
  end
  resources :sale_reports, only: [:index, :destroy]
  resources :product_reports
  resources :vendor_reports
  resources :purchased_item_reports
  resources :purchased_sale_reports
  resources :purchased_items do
    collection do
      get 'excel_upload'
      post 'import_items'
      post 'get_barcode'
      get 'fetch_product_detail'
      get 'fetch_barcode_detail'
    end
  end
  resources :products do
    collection do
      get 'fetch_product_vendor_wise'
      get 'excel_upload'
      post 'import_products'
      get 'append_product'
      get 'append_vendor'
      get 'fetch_product_detail'
    end
  end
  get 'billing', to: 'billings#get_billing_form'
  get 'billing_for_kitchen', to: 'kitchen_billings#get_billing_form'
  get 'kitchen_billings/append_items', to: 'kitchen_billings#append_items'
  get 'kitchen_billings/fetch_item_detail', to: 'kitchen_billings#fetch_item_detail'
  post 'billings/billing_for_product', to: 'billings#billing_for_product'
  get 'purchased_billing', to: 'purchased_billings#get_billing_form'
  post 'purchased_billings/billing_for_product', to: 'purchased_billings#billing_for_product'
  devise_for :admins
  resources :kitchens do
    collection do
      get 'fetch_menu_category_wise'
    end
  end

end

app/models/vendor.rb
class Vendor < ApplicationRecord
  validates :name, presence: { message: "Cant be Blanck" }
  has_many :products, dependent: :destroy
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :authenticate_admin!
  before_action :load_vendor, only: [:edit, :update, :destroy]

  def index
    @co_header = "Listing Vendors"
    @vendors = Vendor.all
  end

  def new
    @co_header = "New Vendor"
    @vendor = Vendor.new
  end
  def create
    @vendor = Vendor.new(vendor_params)
    if @vendor.save
      flash[:success] = "Vendor Created Succussfully"
      redirect_to vendors_path
    else
      flash[:danger_messages] = @vendor.errors.full_messages
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @vendor.update(vendor_params)
      flash[:success] = "Vendor Updated Succussfully"
      redirect_to vendors_path
    else
      flash[:danger_messages] = @vendor.errors.full_messages
      render :edit
    end
  end

  def destroy
    @vendor.destroy
    flash[:success] = "Vendor Deleted Succussfully"
    redirect_to vendors_path
  end

  def fetch_vendor_amount
    if params[:vendor_id].present? && params[:product_id].present? && params['date_range'].present?
      from_date, to_date = from_date_and_to_date params['date_range']
      @vendor_amounts = VendorAmount.where(vendor_id: params[:vendor_id], product_id: params[:product_id], created_at: from_date..to_date).order('created_at desc')
    elsif params[:vendor_id].present? && params['date_range'].present?
      from_date, to_date = from_date_and_to_date params['date_range']
      @vendor_amounts = VendorAmount.where(vendor_id: params[:vendor_id], created_at: from_date..to_date).order('created_at desc')
    elsif params[:product_id].present? && params['date_range'].present?
      from_date, to_date = from_date_and_to_date params['date_range']
      @vendor_amounts = VendorAmount.where(product_id: params[:product_id], created_at: from_date..to_date).order('created_at desc')
    elsif params[:vendor_id].present? && params[:product_id].present?
      @vendor_amounts = VendorAmount.where(vendor_id: params[:vendor_id], product_id: params[:product_id]).order('created_at desc')
    elsif params['date_range'].present?
      from_date, to_date = from_date_and_to_date params['date_range']
      @vendor_amounts = VendorAmount.where(created_at: from_date..to_date).order('created_at desc')
    elsif params[:vendor_id].present?
      @vendor_amounts = VendorAmount.where(vendor_id: params[:vendor_id]).order('created_at desc')
    elsif params[:product_id].present?
      @vendor_amounts = VendorAmount.where(product_id: params[:product_id]).order('created_at desc')
    else
      @vendor_amounts = VendorAmount.all.order('created_at desc')
    end
    if params[:format] == "pdf"
      @report_name = "#{Vendor.find_by(id: params[:vendor_id]).name rescue nil} Amount Report"
      @check_condition_in_pdf = "Vendor Amount"
      @sold_products = @vendor_amounts
      respond_to do |format|
        format.html
        format.pdf do
          render pdf: "Sales Report",
          page_size: 'A4',
          template: "sale_reports/sales_report.pdf.erb",
          orientation: "Landscape",
          layout: "sales_report_pdf.html.erb",
          lowquality: true,
          zoom: 1,
          dpi: 65,
          footer: { html: { template: "sale_reports/footer.pdf.erb" } },
          header: { html: { template: "sale_reports/header.pdf.erb" } }
        end
      end
    end
  end

  def from_date_and_to_date date_range
    to_date = date_range.split("-")[1].strip.to_date.end_of_day
    from_date = date_range.split("-")[0].strip.to_date.beginning_of_day
    [from_date, to_date]
  end

  def delete_vendor_amount
    vendor_amount_id = params[:vendor_amount_id].to_i
    amount_result = VendorAmount.find_by(id: vendor_amount_id)
    amount_result.destroy if amount_result.present?
    flash[:success] = "Vendor amount deleted successfully!"
    redirect_to fetch_vendor_amount_vendors_path(vendor_id: params[:vendor_id])
  end

  private

  def load_vendor
    @vendor = Vendor.find_by(id: params[:id])
  end

  def vendor_params
    params.require(:vendor).permit(:name, :email, :mobile, :gstin)
  end
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/_form.html.erb
<%= form_with model: @vendor, local: true do |f| %>
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-4">
      <%= f.label :name %>
      <%= f.text_field :name , class: "form-control", placeholder: "Enter Vendor Name", required: true %>
    </div>
  </div><br>
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-4">
      <%= f.label :email %>
      <%= f.text_field :email , class: "form-control", placeholder: "Enter Vendor Email", required: true %>
    </div>
  </div><br>
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-4">
      <%= f.label :mobile %>
      <%= f.text_field :mobile , class: "form-control", placeholder: "Enter Vendor Mobile", required: true %>
    </div>
  </div><br>
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-4">
      <%= f.label :gstin, "GSTIN" %>
      <%= f.text_field :gstin , class: "form-control", placeholder: "Enter GST No" %>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <%= f.submit "#{ @vendor.new_record? ? "Create Vendor" : "Update Vendor" }", class: "btn btn-primary" %>
      <br><br>
      <center><%= link_to "Back", :back, class: "back" %></center>
    </div>
  </div>

<% end %>
<style type="text/css">
  body {
    background-image: url(<%= asset_path("blur-background04.jpg")%>);
    background-repeat: no-repeat;
  }
  .back {
    margin-left: -220px;

  }
</style>

app/views/vendors/edit.html.erb
<div class="row co-header">
  <div class="col-md-3">
    <div>Edit Vendor</div>
  </div>
  <div class="col-md-6"></div>
  <div class="col-md-3">
    <div><%= @co_header_new%></div>
  </div>
</div>

<%= render 'form'%>

app/views/vendors/fetch_vendor_amount.html.erb
<% content_for :co_header do %>
  <div class="row co-header">
    <div class="col-md-3">
      <div><%= "Vendors Amount > #{Vendor.find_by(id: params[:vendor_id].to_i).name rescue nil}"%></div>
    </div>
    <div class="col-md-6"></div>
    <div class="col-md-3">
      <div></div>
    </div>
  </div>
<% end %>
<%= form_tag fetch_vendor_amount_vendors_path(vendor_id: params[:vendor_id]), method: :get, name: "sale-report" do %>
  <div class="row">
    <%= hidden_field_tag 'vendor_id', params[:vendor_id] %>
    <div class="col-md-3">
      <%= label_tag :product_id, "Select Product Name" %><br>
      <%= select_tag :product_id, options_from_collection_for_select(Product.where(vendor_id: params[:vendor_id]), 'id', 'name', params[:product_id].present? ? params[:product_id] : 'All'), include_blank: "All", class: 'form-control', onchange: 'this.form.submit();' %>
    </div>
    <div class="col-md-3" style="width: 230px">
      <label for="reportDateRange">Duration</label><br>
      <div class="calendar-icon">
      <i class="fa fa-calendar "></i></div>
      <%= text_field_tag "date_range", params["date_range"], id: "date-range", class: "form-control text-right" %>
    </div>
  </div>
<% end %>
<br><br>
<div class="row">
  <div class="col-md-12">
    <table id="custom-table">
      <thead>
        <tr>
          <th width="60px">SI No.</th>
          <th>Product Name</th>
          <th width="16%">Sold Date</th>
          <th width="13%">Sold Price</th>
          <th width="8%">Quantity</th>
          <th>Sold Value</th>
          <th>Tax %</th>
          <th>Tax Amount</th>
          <th>Vendor Amount</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% if @vendor_amounts.present? %>
          <% count = 0 %>
          <% @grand_vendor_amount = 0 %>
          <% @grand_tax_amount = 0 %>
          <% @grand_sol_value = 0 %>
          <% @vendor_amounts.each do |sold_product| %>
            <% count += 1 %>
            <tr>
              <% product_detail = Product.find_by(id: sold_product.product_id) %>
              <% vendor_detail = Vendor.find_by(id: sold_product.vendor_id) %>
              <% tax_amount = sold_product.tax_amount.present? ? sold_product.tax_amount : 0 %>
              <% vendor_amount = sold_product.vendor_amount.present? ? sold_product.vendor_amount : sold_product.sold_amount %>
              <% tax_percentage = sold_product.tax_percentage.present? ? sold_product.tax_percentage : 0 %>
              <% @grand_vendor_amount = @grand_vendor_amount + vendor_amount %>
              <% @grand_tax_amount = @grand_tax_amount + tax_amount %>
              <% @grand_sol_value = @grand_sol_value + sold_product.sold_amount.to_f %>
              <td><%= count %></td>
              <td><%= product_detail.name rescue nil %></td>
              <td><%= sold_product.created_at.strftime("%m-%d-%Y %I:%M %p") %></td>
              <td><%= "Rs.#{number_with_precision(product_detail.sale_price, precision: 2) rescue nil}" %></td>
              <td style="text-align: center;"><%= sold_product.quantity rescue nil %></td>
              <td><%= "Rs.#{number_with_precision(sold_product.sold_amount, precision: 2) rescue nil}" %></td>
              <td><%= number_with_precision(tax_percentage, precision: 2) rescue nil %></td>
              <td><%= "Rs.#{number_with_precision(tax_amount, precision: 2) rescue nil}" %></td>
              <td><%= "Rs.#{number_with_precision(vendor_amount, precision: 2) rescue nil}" %></td>
              <td><center><%= link_to image_tag("trash.png"), delete_vendor_amount_vendors_path(vendor_amount_id: sold_product.id, vendor_id: params[:vendor_id]), data: { confirm: 'Do you want to delete this Item?' } %></center></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
      <tr>
        <td colspan="2"><strong>Grand Total</strong></td>
        <td></td>
        <td></td>
        <td></td>
        <td><strong><%= "Rs.#{number_with_precision(@grand_sol_value.present? ? @grand_sol_value : 0, precision: 2) rescue nil}" %></strong></td>
        <td></td>
        <td><strong><%= "Rs.#{number_with_precision(@grand_tax_amount.present? ? @grand_tax_amount : 0, precision: 2) rescue nil}" %></strong></td>
        <td><strong><%= "Rs.#{number_with_precision(@grand_vendor_amount.present? ? @grand_vendor_amount : 0, precision: 2) rescue nil}" %></strong></td>
        <td></td>
      </tr>
    </table>
  </div>
</div>
<div class="row">
  <div class="col-md-1">
    <%= link_to 'Generate PDF', fetch_vendor_amount_vendors_path(format: :pdf, vendor_id: params[:vendor_id], product_id: params[:product_id], date_range: params[:date_range]), class: "btn btn-success", target: "_blank" %>
  </div>
</div>
<br><br><br>
<script type="text/javascript">
  $('#product_id').select2();
  $('#custom-table').dataTable();
  $('#date-range').daterangepicker({
    opens: 'left',
    ranges: {
      'Today': [moment(), moment()],
      'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
      'Last 7 Days': [moment().subtract(6, 'days'), moment()],
      'Last 30 Days': [moment().subtract(29, 'days'), moment()],
      'This Month': [moment().startOf('month'), moment().endOf('month')],
      'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
    },
    locale: { format: 'DD/MM/YYYY'}
  })
  $(document).ready(function() {
    $('#date-range').on('change', function() {
      document.forms['sale-report'].submit();
    });
    document.getElementById("date-range").value = "<%= params["date_range"] %>";
  });
</script>
<style type="text/css">
  .select2-container .select2-selection--single {
    height: 39px;
    padding-top: 5px
  }
  .select2-selection__arrow {
    margin-top: 5px;
  }
  #date-range {
    margin-top: -30px;
  }
  .calendar-icon {
    margin-left: 12px;
    margin-top: 10px;
  }
</style>

app/views/vendors/index.html.erb
<% content_for :co_header do %>
  <div class="row co-header">
    <div class="col-md-3">
      <div><%= link_to "Dashboard", root_path %> > <%= @co_header%></div>
    </div>
    <div class="col-md-6"></div>
    <div class="col-md-3">
      <div><%= link_to "New Vendor", new_vendor_path, class: "btn btn-success btn-xs", style: "margin-left:-30px;margin-top:-8px;"%></div>
    </div>
  </div>
<% end %>
<table id="custom-table">
  <thead>
    <tr>
      <th>SI No.</th>
      <th>Name</th>
      <th>Email</th>
      <th>Mobile</th>
      <th>GSTIN</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
    <tbody>
      <% if @vendors.present? %>
        <% count = 0 %>
        <% @vendors.each do |vendor|%>
          <% count += 1 %>
          <tr>
            <td><%= count %></td>
            <td><%= vendor.name %></td>
            <td><%= vendor.email %></td>
            <td><%= vendor.mobile %></td>
            <td><%= vendor.gstin %></td>
            <td><center><%= link_to image_tag("edit.png"), edit_vendor_path(vendor) %></center></td>
            <td><center><%= link_to image_tag("trash.png"), vendor_path(vendor), method: :delete, data: { confirm: 'Do you want to delete this Vendor?' } %></center></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
</table>
<script type="text/javascript">
  $("#custom-table").dataTable();
</script>

app/views/vendors/new.html.erb
<%= render 'layouts/co_header'%>
<%= render 'form'%>

app/views/vendors/show.html.erb
<h1>Vendors#show</h1>
<p>Find me in app/views/vendors/show.html.erb</p>

app/views/vendors/update.html.erb
<h1>Vendors#update</h1>
<p>Find me in app/views/vendors/update.html.erb</p>