config/routes.rb
Rails.application.routes.draw do

  root 'dash_boards#index'
  resources :vendors do
    collection do
      get 'fetch_vendor_amount'
      get 'delete_vendor_amount'
    end
  end
  resources :sale_reports, only: [:index, :destroy]
  resources :product_reports
  resources :vendor_reports
  resources :purchased_item_reports
  resources :purchased_sale_reports
  resources :purchased_items do
    collection do
      get 'excel_upload'
      post 'import_items'
      post 'get_barcode'
      get 'fetch_product_detail'
      get 'fetch_barcode_detail'
    end
  end
  resources :products do
    collection do
      get 'fetch_product_vendor_wise'
      get 'excel_upload'
      post 'import_products'
      get 'append_product'
      get 'append_vendor'
      get 'fetch_product_detail'
    end
  end
  get 'billing', to: 'billings#get_billing_form'
  get 'billing_for_kitchen', to: 'kitchen_billings#get_billing_form'
  get 'kitchen_billings/append_items', to: 'kitchen_billings#append_items'
  get 'kitchen_billings/fetch_item_detail', to: 'kitchen_billings#fetch_item_detail'
  post 'billings/billing_for_product', to: 'billings#billing_for_product'
  get 'purchased_billing', to: 'purchased_billings#get_billing_form'
  post 'purchased_billings/billing_for_product', to: 'purchased_billings#billing_for_product'
  devise_for :admins
  resources :kitchens do
    collection do
      get 'fetch_menu_category_wise'
    end
  end

end

app/models/product.rb
class Product < ApplicationRecord
  require 'roo'

  belongs_to :vendor
  validates :vendor_id, presence: { message: "Vendor must be presence" }

  def self.import_product(file)
    temp_sheet = open_spreadsheet(file)
    return false if temp_sheet == false
    spreadsheet = temp_sheet.sheet('Products') rescue nil
    return false if spreadsheet == nil
    result = insert_data_to_database spreadsheet
    Product.import result if result.present?
    true
  end

  def self.open_spreadsheet file
    case File.extname(file.original_filename)
    when ".csv" then Csv.new(file.path, nil, :ignore)
    when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
    when ".xlsx" then Roo::Excelx.new(file.path)
    else return false
    end
  end

  def self.insert_data_to_database spreadsheet
    @product = []
    spreadsheet.each.with_index do |sheet, index|
      next if index == 0
      next if sheet[2] == "" || sheet[3] == "" || sheet[4] == "" || sheet[6] == "" || sheet[7] == "" || sheet[8] == "" || sheet[2] == nil || sheet[3] == nil || sheet[4] == nil || sheet[6] == nil || sheet[7] == nil || sheet[8] == nil
      vendor_detail = Vendor.find_by(name: sheet[3])
      vendor_id = vendor_detail.id if vendor_detail.present?
      @product << Product.new( sku_no: sheet[1], name: sheet[2], category: sheet[4], barcode: sheet[5], quantity: sheet[6], base_price: sheet[7], sale_price: sheet[8], gst_percentage: sheet[8], cost: sheet[10], hsn_code: sheet[11], vendor_id: vendor_id )
    end
    @product
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_admin!
  before_action :load_product, only: [:show, :edit, :update, :destroy]

  def index
    @vendors = Vendor.all
    @products = Product.all
    respond_to do |format|
      format.html
      format.xlsx {
        response.headers['Content-Disposition'] = 'attachment; filename="sample_products.xlsx"'
      }
    end
  end

  def show

  end

  def new
    @co_header = "New Product"
    @product = Product.new
  end

  def edit
    @co_header = "Edit Product"
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:success] = "Product Created Successfully!"
      redirect_to fetch_product_vendor_wise_products_path(vendor_id: @product.vendor_id)
    else
      flash[:danger_messages] = @product.errors.full_messages
      render :new
    end
  end

  def update
    if @product.update(product_params)
      flash[:success] = "Product Updated Successfully!"
      redirect_to fetch_product_vendor_wise_products_path(vendor_id: @product.vendor_id)
    else
      flash[:danger_messages] = @product.errors.full_messages
      render :edit
    end
  end

  def destroy
    @product.destroy
    flash[:success] = "Product Deleted Successfully!"
    redirect_to products_path
  end

  def fetch_product_vendor_wise
    @vendor_wise_products = Product.joins(:vendor).where(vendor_id: params[:vendor_id])
  end

  def excel_upload
    @co_header = "Excel Upload"
  end

  def import_products
    if Product.import_product(params[:file])
      flash[:success] = "Product Uploaded Successfully!"
      redirect_to products_path
    else
      flash[:danger] = "Invalid Template!"
      redirect_to excel_upload_products_path
    end
  end

  def append_product
    result = {}
    if params[:vendor_id] && params[:vendor_id].to_i != 0
      @products = Product.where(vendor_id: params[:vendor_id].to_i)
      if @products.present?
        @products.each do |product|
          result[product.id] = "#{product.name} - Rs.#{sprintf "%.2f", product.sale_price.to_f}"
        end
      end
    end
    respond_to do |format|
      format.json { render json: result.to_json }
    end
  end

  def append_vendor
    result = []
    if params[:vendor_id].present? && params[:vendor_id].to_i != 0
      vendor = Vendor.find_by(id: params[:vendor_id].to_i)
      result << vendor.name << vendor.mobile << vendor.gstin
    end
    respond_to do |format|
      format.json { render json: result.to_json }
    end
  end

  def fetch_product_detail
    result = []
    if params[:barcode].present? && params[:vendor_id].present?
      product = Product.where(barcode: params[:barcode], vendor_id: params[:vendor_id]).first
      result << product.id << product.name << product.sale_price.to_f << product.quantity << product.vendor.name if product.present?
    else
      product = Product.find_by(id: params[:product_id].to_i)
      if product.present?
        vendor_name = product.vendor.name
        result << product.id << product.name << product.sale_price.to_f << product.quantity << vendor_name
      end
    end
    respond_to do |format|
      format.json { render json: result.to_json }
    end
  end

  private

    def load_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :sku_no, :category, :barcode, :quantity, :base_price, :sale_price, :gst_percentage, :cost, :hsn_code, :vendor_id)
    end

end

app/views/products/_form.html.erb
<%= form_with model: @product, local: true do |f| %>
  <div class="row">
    <div class="col-md-4">
      <%= f.label :name, "Product Name", class: "required-field" %><br>
      <%= f.text_field :name , class: "form-control", required: true, placeholder: "Enter Product Name" %>
    </div>
    <div class="col-md-4">
      <%= f.label :sku_no, class: "required-field" %><br>
      <%= f.text_field :sku_no , class: "form-control", required: true, placeholder: "Enter Sku No" %>
    </div>
    <div class="col-md-4">
      <%= f.label :category, class: "required-field" %><br>
      <%= f.text_field :category, class: "form-control", required: true, placeholder: "Enter category name Example : Jeans, Tshirt" %>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-4">
      <%= f.label :barcode, class: "required-field" %><br>
      <%= f.text_field :barcode, class: "form-control", required: true, placeholder: "Enter Barcode" %>
    </div>
    <div class="col-md-4">
      <%= f.label :quantity, class: "required-field" %><br>
      <%= f.text_field :quantity, class: "form-control", required: true, placeholder: "Enter Quantity" %>
    </div>
    <div class="col-md-4">
      <%= f.label :base_price, class: "required-field" %><br>
      <%= f.text_field :base_price, class: "form-control", required: true, placeholder: "Enter Base Price" %>
    </div>
  </div><br>
  <div class="row">
    <div class="col-md-4">
      <%= f.label :sale_price, class: "required-field" %><br>
      <%= f.text_field :sale_price, class: "form-control", required: true, placeholder: "Enter Sale Price" %>
    </div>
    <div class="col-md-4">
      <%= f.label :gst_percentage, class: "required-field" %><br>
      <%= f.text_field :gst_percentage, class: "form-control", required: true, placeholder: "Enter Gst Percentage" %>
    </div>
    <div class="col-md-4">
      <%= f.label :hsn_code, class: "required-field" %><br>
      <%= f.text_field :hsn_code, class: "form-control", required: true, placeholder: "Enter Hsn Code" %>
    </div>
  </div><br>
  <div class="row">
    <div class="col-md-4">
      <%= f.label :cost, class: "required-field" %><br>
      <%= f.text_field :cost, class: "form-control", required: true, placeholder: "Enter the cost of product" %>
    </div>
    <div class="col-md-4">
      <%= f.label :vendor_id, class: "required-field" %><br>
      <%= f.select :vendor_id, options_for_select(Vendor.all.collect { |d| [d.name, d.id]}, selected: @product.vendor_id), {include_blank: 'Select Vendor Name'}, { class: 'form-control', required: true } %>
    </div>
  </div><br>

  <br>
  <center><%= f.submit "#{@product.new_record? ? 'Add Product' : 'Update Product'}", class: "btn btn-success" %></center><br>
  <center><%= link_to "Back", :back %></center>
<% end %>
<script type="text/javascript">
  $(document).ready(function() {
  $('#product_vendor_id').select2({
    placeholder: "Choose a Vendor"
  });
});
</script>
<style type="text/css">
  body {
    background: #E3E6E3;
  }
  .product_vendor_id {
    background-color: red;
  }
  .select2-selection__arrow{
    background-color: grey;
  }
</style>

app/views/products/edit.html.erb
<% content_for :co_header do %>
  <div class="row co-header">
    <div class="col-md-3">
      <div><%= "#{ Vendor.find_by(id: params[:vendor_id]).name rescue nil } >"%> &nbsp;<%= @co_header%></div>
    </div>
    <div class="col-md-6"></div>
    <div class="col-md-3">
    </div>
  </div>
<% end %>
<%= render "form" %>

app/views/products/excel_upload.html.erb
<% content_for :co_header do %>
  <div class="row co-header">
    <div class="col-md-3">
      <div>Products > Excel Upload</div>
    </div>
    <div class="col-md-3">
    </div>
    <div class="col-md-3">
    </div>
    <div class="col-md-3">
      <div><%= link_to "Add Product", new_product_path, class: "btn btn-success btn-xs", style: "margin-left:-30px;margin-top:-8px;"%></div>
    </div>
  </div>
<% end %>
<br><br><br>
<%= form_tag import_products_products_path, multipart: true, id: "upload-excel-product" do %>
  <br>
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4"><%= image_tag('upload.png', class: "image-excel-upload")%></div>
    <div class="col-md-4"></div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <%= file_field_tag :file, class: "upload-field", required: true%>
    </div>
    <div class="col-md-4"></div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-1">
      <%= link_to "Close", products_path, class: "btn btn-danger btn-xs back" %>
    </div>
    <div class="col-md-4">
      <%= submit_tag "Upload", class: "btn btn-success btn-xs", id: "submit-upload" %>

    </div>
    <div class="col-md-3"></div>
  </div>
  <br>
<% end %>
<style type="text/css">
  .back {
    margin-left: 220px;
  }
  .image-excel-upload{
    margin-left: -20px
  }
  #submit-upload{
    margin-left: -7px;
  }
  .upload-field {
    border: 2px solid gray;
    color: gray;
    margin-left:-47px;
    background-color: white;
    padding: 8px 10px;
    border-radius: 8px;
    font-size: 13px;
    font-weight: bold;
  }
  #upload-excel-product {
    width: 550px;
    margin-left:230px;
    /*background-color: grey;*/
    border-style: dotted
  }
</style>

app/views/products/fetch_product_vendor_wise.html.erb
<% content_for :co_header do %>
  <div class="row co-header">
    <div class="col-md-3">
      <div style="font-weight: bold"><%= "Vendors > #{Vendor.find_by(id: params[:vendor_id].to_i).name}" %></div>
    </div>
    <div class="col-md-4"></div>
    <div class="col-md-2">
      <div><%= link_to "Excel Upload", excel_upload_products_path, class: "btn btn-success btn-xs", style: "margin-left:-40px;margin-top:-8px;font-size:10px;"%></div>
    </div>
    <div class="col-md-3">
      <div><%= link_to "New Product", new_product_path(vendor_id: params[:vendor_id]), class: "btn btn-success btn-xs", style: "margin-left:-40px;margin-top:-8px;font-size:10px;"%></div>
    </div>
</div>
<% end %>
<table id="custom-table">
  <thead>
    <tr>
      <th>SI No.</th>
      <th>Product Name</th>
      <th>Sku No</th>
      <th>Category</th>
      <th>Barcode</th>
      <th>Quantity</th>
      <th>Base Price</th>
      <th>Sale Price</th>
      <th>Gst Percentage</th>
      <th>Cost</th>
      <th>Hsn Code</th>
      <th>Vendor</th>
      <th></th>
      <th>Operation</th>
    </tr>
  </thead>
  <tbody>
    <% if @vendor_wise_products.present? %>
      <% count = 0 %>
      <% @vendor_wise_products.each do |product|%>
        <% count += 1 %>
        <tr>
          <td><%= count %></td>
          <td><%= product.name %></td>
          <td><%= product.sku_no %></td>
          <td><%= product.category %></td>
          <td><%= product.barcode %></td>
          <td><%= product.quantity %></td>
          <td><%= "Rs.#{number_with_precision(product.base_price, precision: 2)}" %></td>
          <td><%= "Rs.#{number_with_precision(product.sale_price, precision: 2)}" %></td>
          <td><%= "#{number_with_precision(product.gst_percentage, precision: 2)} %" %></td>
          <td><%= "Rs.#{number_with_precision(product.cost, precision: 2)}" %></td>
          <td><%= product.hsn_code %></td>
          <td><%= product.vendor.name %></td>
          <td><center><%= link_to image_tag("edit.png"), edit_product_path(product, vendor_id: product.vendor_id) %></center></td>
          <td><center><%= link_to image_tag("trash.png"), product_path(product), method: :delete, data: { confirm: 'Do you want to delete this Product?' } %></center></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<script type="text/javascript">
  $(document).ready( function () {
    $('#custom-table').DataTable();
  });
</script>

app/views/products/index.html.erb
<% content_for :co_header do %>
  <div class="row co-header">
    <div class="col-md-3">
      <div>Vendor products</div>
    </div>
    <div class="col-md-3">
    </div>
    <div class="col-md-3">
    </div>
    <div class="col-md-3">
      <div><%= link_to "Add Product", new_product_path, class: "btn btn-success btn-xs", style: "margin-left:-30px;margin-top:-8px;"%></div>
    </div>
  </div>
<% end %>
<table id="custom-table">
  <thead>
    <tr>
      <th>SI No.</th>
      <th>Product Name</th>
      <th>SKU No</th>
      <th>Category</th>
      <th>Barcode</th>
      <th>Quantity</th>
      <th>Base Price</th>
      <th>Sale Price</th>
      <th>GST %</th>
      <th>Cost</th>
      <th>HSN Code</th>
      <th>Vendor</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% if @products.present? %>
      <% count = 0 %>
      <% @products.each do |product|%>
        <% count += 1 %>
        <tr>
          <td><%= count %></td>
          <td><%= product.name %></td>
          <td><%= product.sku_no %></td>
          <td><%= product.category %></td>
          <td><%= product.barcode %></td>
          <td><%= product.quantity %></td>
          <% base_price = product.base_price.present? ? product.base_price : 0 %>
          <% sale_price = product.sale_price.present? ? product.sale_price : 0 %>
          <% gst_percentage = product.gst_percentage.present? ? product.gst_percentage : 0 %>
          <% cost = product.cost.present? ? product.cost : 0 %>
          <td><%= "Rs.#{number_with_precision(base_price, precision: 2)}" %></td>
          <td><%= "Rs.#{number_with_precision(sale_price, precision: 2)}" %></td>
          <td><%= "#{number_with_precision(gst_percentage, precision: 2)} %" %></td>
          <td><%= "Rs.#{number_with_precision(cost, precision: 2)}" %></td>
          <td><%= product.hsn_code.present? ? product.hsn_code : '-' %></td>
          <td><%= product.vendor.name %></td>
          <td><center><%= link_to image_tag("edit.png"), edit_product_path(product, vendor_id: product.vendor_id) %></center></td>
          <td><center><%= link_to image_tag("trash.png"), product_path(product), method: :delete, data: { confirm: 'Do you want to delete this Product?' } %></center></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<script type="text/javascript">
  $(document).ready( function () {
    $('#custom-table').DataTable();
  });
</script>

app/views/products/new.html.erb
<% content_for :co_header do %>
  <div class="row co-header">
    <div class="col-md-3">
      <div><%= @co_header%></div>
    </div>
    <div class="col-md-6"></div>
    <div class="col-md-3">
    </div>
  </div>
<% end %>
<%= render "form" %>